### ISSUE TITLE
No page rendered

### ISSUE THREAD

**Issue by ZhouTimeMachine** [TonyCrane/slide-template#1]
![error](https://github.com/TonyCrane/slide-template/assets/99057383/4842191f-343c-42eb-a4c7-fb6f7464b8a3)
Like this.
I think it is due to update of template.html of reveal-md.

Compare old version (line 37-39 in this repo)
```html
<div class="reveal">
  <div class="slides">{{{slides}}}</div>
</div>
```

with new version (line 35-43 in https://github.com/webpro/reveal-md/blob/main/lib/template/reveal.html)
```html
<div class="reveal">
  <div class="slides">
    <section data-markdown {{{slidifyAttributes}}}>
      <textarea data-template>
        {{{markdown}}}
      </textarea>
    </section>
  </div>
</div>
```

I hope this may help.

**Comment by TonyCrane** [comment]
Fixed by #2
